In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)

In [8]:
fake_df = pd.read_csv("../data/Fake.csv")
true_df = pd.read_csv("../data/True.csv")

In [9]:
fake_df.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [10]:
true_df.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [11]:
print(fake_df.shape, true_df.shape)

(23481, 4) (21417, 4)

In [12]:
fake_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23481 entries, 0 to 23480
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    23481 non-null  object
 1   text     23481 non-null  object
 2   subject  23481 non-null  object
 3   date     23481 non-null  object
dtypes: object(4)
memory usage: 733.9+ KB

In [13]:
true_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21417 entries, 0 to 21416
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    21417 non-null  object
 1   text     21417 non-null  object
 2   subject  21417 non-null  object
 3   date     21417 non-null  object
dtypes: object(4)
memory usage: 669.4+ KB

In [14]:
fake_df.isnull().sum()

title      0
text       0
subject    0
date       0
dtype: int64

In [15]:
true_df.isnull().sum()

title      0
text       0
subject    0
date       0
dtype: int64

In [16]:
fake_df.duplicated().sum()

np.int64(3)

In [17]:
true_df.duplicated().sum()

np.int64(206)

In [18]:
fake_df.describe(include="all")

,title,text,subject,date
count,23481,23481,23481,23481
unique,17903,17455,6,1681
top,MEDIA IGNORES Time That Bill Clinton FIRED His...,,News,"May 10, 2017"
freq,6,626,9050,46

In [19]:
true_df.describe(include="all")

,title,text,subject,date
count,21417,21417,21417,21417
unique,20826,21192,2,716
top,Factbox: Trump fills top jobs for his administ...,(Reuters) - Highlights for U.S. President Dona...,politicsNews,"December 20, 2017"
freq,14,8,11272,182

In [20]:
fake_df["label"] = 0
true_df["label"] = 1

In [21]:
df = pd.concat([fake_df, true_df], ignore_index=True)

In [22]:
df.head()

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0

In [23]:
df.shape

(44898, 5)

In [24]:
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

In [25]:
df = df.drop_duplicates()

In [26]:
df.shape

(44689, 5)

In [27]:
import re
import string

In [28]:
df_clean = df.copy()

In [29]:
df_clean["content"] = df_clean["title"] + " " + df_clean["text"]

In [30]:
df_clean[["title", "text", "content"]].head()

,title,text,content
0,Ben Stein Calls Out 9th Circuit Court: Committ...,"21st Century Wire says Ben Stein, reputable pr...",Ben Stein Calls Out 9th Circuit Court: Committ...
1,Trump drops Steve Bannon from National Securit...,WASHINGTON (Reuters) - U.S. President Donald T...,Trump drops Steve Bannon from National Securit...
2,Puerto Rico expects U.S. to lift Jones Act shi...,(Reuters) - Puerto Rico Governor Ricardo Rosse...,Puerto Rico expects U.S. to lift Jones Act shi...
3,OOPS: Trump Just Accidentally Confirmed He Le...,"On Monday, Donald Trump once again embarrassed...",OOPS: Trump Just Accidentally Confirmed He Le...
4,Donald Trump heads for Scotland to reopen a go...,"GLASGOW, Scotland (Reuters) - Most U.S. presid...",Donald Trump heads for Scotland to reopen a go...

In [31]:
df_clean = df_clean[["content", "label"]]

In [32]:
def clean_text(text):
    
    # Convert to lowercase
    text = text.lower()

    # Remove URLs
    text = re.sub(r"http\S+|www\S+", "", text)

    # Remove HTML tags
    text = re.sub(r"<.*?>", "", text)

    # Remove punctuation
    text = text.translate(str.maketrans("", "", string.punctuation))

    # Remove numbers
    text = re.sub(r"\d+", "", text)

    # Remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text

In [33]:
df_clean["content"] = df_clean["content"].apply(clean_text)

In [34]:
df_clean.head()

                                             content  label
0  ben stein calls out th circuit court committed...      0
1  trump drops steve bannon from national securit...      1
2  puerto rico expects us to lift jones act shipp...      1
3  oops trump just accidentally confirmed he leak...      0
4  donald trump heads for scotland to reopen a go...      1

In [35]:
print("Before Cleaning:\n")
print(df["title"][0])
print(df["text"][0])

print("\n" + "=" * 100 + "\n")

print("After Cleaning:\n")
print(df_clean["content"][0])

Before Cleaning:

Ben Stein Calls Out 9th Circuit Court: Committed a ‘Coup d’état’ Against the Constitution
21st Century Wire says Ben Stein, reputable professor from, Pepperdine University (also of some Hollywood fame appearing in TV shows and films such as Ferris Bueller s Day Off) made some provocative statements on Judge Jeanine Pirro s show recently. While discussing the halt that was imposed on President Trump s Executive Order on travel. Stein referred to the judgement by the 9th Circuit Court in Washington state as a  Coup d tat against the executive branch and against the constitution.  Stein went on to call the Judges in Seattle  political puppets  and the judiciary  political pawns. Watch the interview below for the complete statements and note the stark contrast to the rhetoric of the leftist media and pundits who neglect to note that no court has ever blocked any Presidential orders in immigration in the past or discuss the legal efficacy of the halt or the actual text of the Executive Order.READ MORE TRUMP NEWS AT: 21st Century Wire Trump FilesSUPPORT OUR WORK BY SUBSCRIBING & BECOMING A MEMBER @21WIRE.TV

====================================================================================================

After Cleaning:

ben stein calls out th circuit court committed a ‘coup d’état’ against the constitution st century wire says ben stein reputable professor from pepperdine university also of some hollywood fame appearing in tv shows and films such as ferris bueller s day off made some provocative statements on judge jeanine pirro s show recently while discussing the halt that was imposed on president trump s executive order on travel stein referred to the judgement by the th circuit court in washington state as a coup d tat against the executive branch and against the constitution stein went on to call the judges in seattle political puppets and the judiciary political pawns watch the interview below for the complete statements and note the stark contrast to the rhetoric of the leftist media and pundits who neglect to note that no court has ever blocked any presidential orders in immigration in the past or discuss the legal efficacy of the halt or the actual text of the executive orderread more trump news at st century wire trump filessupport our work by subscribing becoming a member wiretv

In [40]:
import nltk

nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")
nltk.download("wordnet")
nltk.download("omw-1.4")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\SUMANTH\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\SUMANTH\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\SUMANTH\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\SUMANTH\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\SUMANTH\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [41]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer

In [42]:
sample = df_clean["content"].iloc[0]

print(sample)

ben stein calls out th circuit court committed a ‘coup d’état’ against the constitution st century wire says ben stein reputable professor from pepperdine university also of some hollywood fame appearing in tv shows and films such as ferris bueller s day off made some provocative statements on judge jeanine pirro s show recently while discussing the halt that was imposed on president trump s executive order on travel stein referred to the judgement by the th circuit court in washington state as a coup d tat against the executive branch and against the constitution stein went on to call the judges in seattle political puppets and the judiciary political pawns watch the interview below for the complete statements and note the stark contrast to the rhetoric of the leftist media and pundits who neglect to note that no court has ever blocked any presidential orders in immigration in the past or discuss the legal efficacy of the halt or the actual text of the executive orderread more trump news at st century wire trump filessupport our work by subscribing becoming a member wiretv

In [43]:
tokens = word_tokenize(sample)

print(tokens)

['ben', 'stein', 'calls', 'out', 'th', 'circuit', 'court', 'committed', 'a', '‘', 'coup', 'd', '’', 'état', '’', 'against', 'the', 'constitution', 'st', 'century', 'wire', 'says', 'ben', 'stein', 'reputable', 'professor', 'from', 'pepperdine', 'university', 'also', 'of', 'some', 'hollywood', 'fame', 'appearing', 'in', 'tv', 'shows', 'and', 'films', 'such', 'as', 'ferris', 'bueller', 's', 'day', 'off', 'made', 'some', 'provocative', 'statements', 'on', 'judge', 'jeanine', 'pirro', 's', 'show', 'recently', 'while', 'discussing', 'the', 'halt', 'that', 'was', 'imposed', 'on', 'president', 'trump', 's', 'executive', 'order', 'on', 'travel', 'stein', 'referred', 'to', 'the', 'judgement', 'by', 'the', 'th', 'circuit', 'court', 'in', 'washington', 'state', 'as', 'a', 'coup', 'd', 'tat', 'against', 'the', 'executive', 'branch', 'and', 'against', 'the', 'constitution', 'stein', 'went', 'on', 'to', 'call', 'the', 'judges', 'in', 'seattle', 'political', 'puppets', 'and', 'the', 'judiciary', 'political', 'pawns', 'watch', 'the', 'interview', 'below', 'for', 'the', 'complete', 'statements', 'and', 'note', 'the', 'stark', 'contrast', 'to', 'the', 'rhetoric', 'of', 'the', 'leftist', 'media', 'and', 'pundits', 'who', 'neglect', 'to', 'note', 'that', 'no', 'court', 'has', 'ever', 'blocked', 'any', 'presidential', 'orders', 'in', 'immigration', 'in', 'the', 'past', 'or', 'discuss', 'the', 'legal', 'efficacy', 'of', 'the', 'halt', 'or', 'the', 'actual', 'text', 'of', 'the', 'executive', 'orderread', 'more', 'trump', 'news', 'at', 'st', 'century', 'wire', 'trump', 'filessupport', 'our', 'work', 'by', 'subscribing', 'becoming', 'a', 'member', 'wiretv']

In [44]:
stop_words = set(stopwords.words("english"))

stemmer = PorterStemmer()

lemmatizer = WordNetLemmatizer()

In [45]:
def preprocess_text(text):

    # Tokenize
    tokens = word_tokenize(text)

    # Remove Stop Words
    tokens = [word for word in tokens if word not in stop_words]

    # Lemmatization
    tokens = [lemmatizer.lemmatize(word) for word in tokens]

    return " ".join(tokens)

In [46]:
df_clean["content"] = df_clean["content"].apply(preprocess_text)

In [47]:
df_clean.head()

                                             content  label
0  ben stein call th circuit court committed ‘ co...      0
1  trump drop steve bannon national security coun...      1
2  puerto rico expects u lift jones act shipping ...      1
3  oops trump accidentally confirmed leaked israe...      0
4  donald trump head scotland reopen golf resort ...      1

In [48]:
from sklearn.model_selection import train_test_split

X = df_clean["content"]
y = df_clean["label"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [49]:
print(X_train.shape)
print(X_test.shape)

print(y_train.shape)
print(y_test.shape)

(35751,)
(8938,)
(35751,)
(8938,)

In [50]:
from sklearn.feature_extraction.text import CountVectorizer

bow = CountVectorizer()

X_train_bow = bow.fit_transform(X_train)
X_test_bow = bow.transform(X_test)

In [51]:
print(X_train_bow.shape)
print(X_test_bow.shape)

(35751, 178856)
(8938, 178856)

In [52]:
from sklearn.naive_bayes import MultinomialNB

nb_bow = MultinomialNB()

nb_bow.fit(X_train_bow, y_train)

MultinomialNB()

In [53]:
y_pred_bow = nb_bow.predict(X_test_bow)

In [54]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred_bow))

Accuracy: 0.9559185500111882

In [55]:
print(classification_report(y_test, y_pred_bow))

              precision    recall  f1-score   support

           0       0.96      0.96      0.96      4696
           1       0.95      0.96      0.95      4242

    accuracy                           0.96      8938
   macro avg       0.96      0.96      0.96      8938
weighted avg       0.96      0.96      0.96      8938

In [56]:
cm = confusion_matrix(y_test, y_pred_bow)

print(cm)

[[4485  211]
 [ 183 4059]]

In [57]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()

In [58]:
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

In [59]:
print(X_train_tfidf.shape)
print(X_test_tfidf.shape)

(35751, 178856)
(8938, 178856)

In [60]:
nb_tfidf = MultinomialNB()

nb_tfidf.fit(X_train_tfidf, y_train)

MultinomialNB()

In [61]:
y_pred_tfidf = nb_tfidf.predict(X_test_tfidf)

In [62]:
print("Accuracy:", accuracy_score(y_test, y_pred_tfidf))

Accuracy: 0.9403669724770642

In [63]:
print(classification_report(y_test, y_pred_tfidf))

              precision    recall  f1-score   support

           0       0.94      0.95      0.94      4696
           1       0.94      0.93      0.94      4242

    accuracy                           0.94      8938
   macro avg       0.94      0.94      0.94      8938
weighted avg       0.94      0.94      0.94      8938

In [64]:
cm = confusion_matrix(y_test, y_pred_tfidf)

print(cm)

[[4446  250]
 [ 283 3959]]

In [65]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(
    max_iter=1000,
    random_state=42
)

In [66]:
lr.fit(X_train_tfidf, y_train)

LogisticRegression(max_iter=1000, random_state=42)

In [67]:
y_pred_lr = lr.predict(X_test_tfidf)

In [68]:
print("Accuracy:", accuracy_score(y_test, y_pred_lr))

Accuracy: 0.9872454687849631

In [69]:
print(classification_report(y_test, y_pred_lr))

              precision    recall  f1-score   support

           0       0.99      0.98      0.99      4696
           1       0.98      0.99      0.99      4242

    accuracy                           0.99      8938
   macro avg       0.99      0.99      0.99      8938
weighted avg       0.99      0.99      0.99      8938

In [70]:
cm = confusion_matrix(y_test, y_pred_lr)

print(cm)

[[4625   71]
 [  43 4199]]

In [71]:
from sklearn.svm import LinearSVC

svm = LinearSVC(random_state=42)

In [72]:
svm.fit(X_train_tfidf, y_train)

LinearSVC(random_state=42)

In [73]:
y_pred_svm = svm.predict(X_test_tfidf)

In [74]:
print("Accuracy:", accuracy_score(y_test, y_pred_svm))

Accuracy: 0.9955247258894607

In [75]:
print(classification_report(y_test, y_pred_svm))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      4696
           1       1.00      1.00      1.00      4242

    accuracy                           1.00      8938
   macro avg       1.00      1.00      1.00      8938
weighted avg       1.00      1.00      1.00      8938

In [76]:
cm = confusion_matrix(y_test, y_pred_svm)

print(cm)

[[4675   21]
 [  19 4223]]

In [78]:
results = {
    "Model": [
        "Naive Bayes (BoW)",
        "Naive Bayes (TF-IDF)",
        "Logistic Regression (TF-IDF)",
        "Linear SVM (TF-IDF)"
    ],
    "Accuracy": [
        accuracy_score(y_test, y_pred_bow),
        accuracy_score(y_test, y_pred_tfidf),
        accuracy_score(y_test, y_pred_lr),
        accuracy_score(y_test, y_pred_svm)
    ]
}

results_df = pd.DataFrame(results)

results_df.sort_values(
    by="Accuracy",
    ascending=False
).reset_index(drop=True)

                          Model  Accuracy
0           Linear SVM (TF-IDF)  0.995525
1  Logistic Regression (TF-IDF)  0.987245
2             Naive Bayes (BoW)  0.955919
3          Naive Bayes (TF-IDF)  0.940367

In [79]:
pip install joblib

Requirement already satisfied: joblib in g:\ai ml projects\fake-news-detection\.venv\lib\site-packages (1.5.3)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.2.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [80]:
import joblib

In [81]:
joblib.dump(svm, "../models/fake_news_model.pkl")

['../models/fake_news_model.pkl']

In [82]:
joblib.dump(tfidf, "../models/tfidf_vectorizer.pkl")

['../models/tfidf_vectorizer.pkl']

In [83]:
import os

os.listdir("../models")

['fake_news_model.pkl', 'tfidf_vectorizer.pkl']

In [84]:
loaded_model = joblib.load("../models/fake_news_model.pkl")

loaded_vectorizer = joblib.load("../models/tfidf_vectorizer.pkl")

In [85]:
news = """
The government announced a new policy today to improve education across the country.
"""

news = clean_text(news)

news = preprocess_text(news)

news_vector = loaded_vectorizer.transform([news])

prediction = loaded_model.predict(news_vector)

print(prediction)

[0]

In [86]:
if prediction[0] == 0:
    print("Fake News")
else:
    print("Real News")

Fake News